spring.application.name=spring-gift
spring.mvc.hiddenmethod.filter.enabled=true

# Import .env file
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret-key=${JWT_SECRET_KEY}

# DB
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Kakao API
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}

spring.h2.console.path=/h2-console
